"""Add visit_briefs table.

Pre-visit summary doctors read before seeing a patient. The
LLM compiles 30 days of timeline data (adherence, side
effects, lab results, recent messages) into:

    - ``summary`` — 2-3 sentence "what's new since last visit"
    - ``talking_points`` JSON list — concrete questions/items
      for the doctor to surface
    - ``red_flags`` JSON list — safety concerns the bot flagged
    - ``key_metrics`` JSON dict — adherence rate, missed-dose
      count, side-effect count for at-a-glance numbers

Briefs are NOT singletons per patient — we store every
generation so doctors can see "compared to the brief from 2
weeks ago, this patient...". ``status`` lifecycles:

    draft (just generated, not surfaced) → sent (returned to
    a doctor at least once) → superseded (newer brief exists
    for the same appointment).

We index on (patient_id, generated_at) for the patient-detail
"recent briefs" widget, and (appointment_id) for the per-appt
lookup the auto-generation flow uses.

Revision ID: 20260508_0033
Revises: 20260508_0032
Create Date: 2026-05-08 19:00:00.000000
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "20260508_0033"
down_revision: Union[str, None] = "20260508_0032"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "visit_briefs",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "patient_id",
            sa.Integer(),
            sa.ForeignKey("patients.id", ondelete="CASCADE"),
            nullable=False,
        ),
        # Optional FK to an appointment — present when the
        # brief was generated for a specific upcoming visit,
        # NULL when generated on-demand from the patient
        # detail page.
        sa.Column(
            "appointment_id",
            sa.Integer(),
            sa.ForeignKey("appointments.id", ondelete="SET NULL"),
            nullable=True,
        ),
        # The doctor the brief was prepared for. Optional —
        # ad-hoc briefs from the ops console don't always have
        # one. When set, ``patient × doctor × generated_at``
        # is the natural triplet for "show this doctor's
        # briefs".
        sa.Column(
            "doctor_id",
            sa.Integer(),
            sa.ForeignKey("doctors.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        # Time window the brief summarises (typically 30 days
        # back from generated_at). Stored explicitly so the UI
        # can label "30-day brief" vs "since last visit".
        sa.Column(
            "window_start",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "window_end",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        # LLM model + tokens used. Lets us compute brief cost
        # post-hoc and audit when a regression in brief
        # quality coincides with a model change.
        sa.Column("llm_model", sa.String(length=64), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        # Structured outputs from the LLM.
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "talking_points",
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'[]'::json"),
        ),
        sa.Column(
            "red_flags",
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'[]'::json"),
        ),
        sa.Column(
            "key_metrics",
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'{}'::json"),
        ),
        # Lifecycle: draft → sent → superseded. We never
        # delete briefs (audit), so superseded is the
        # tombstone.
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
            server_default="draft",
        ),
        sa.Column(
            "generated_by",
            sa.String(length=128),
            nullable=True,
            comment=(
                "Operator id when manually triggered, NULL "
                "when auto-generated by the scheduler."
            ),
        ),
        # Free-form error captured when the LLM call failed.
        # When non-null, summary may be empty / placeholder
        # ("brief generation failed"). UI hides those by
        # default.
        sa.Column("error", sa.Text(), nullable=True),
    )
    op.create_index(
        "ix_visit_briefs_patient_generated",
        "visit_briefs",
        ["patient_id", "generated_at"],
    )
    op.create_index(
        "ix_visit_briefs_appointment",
        "visit_briefs",
        ["appointment_id"],
    )


def downgrade() -> None:
    op.drop_index("ix_visit_briefs_appointment", table_name="visit_briefs")
    op.drop_index(
        "ix_visit_briefs_patient_generated", table_name="visit_briefs"
    )
    op.drop_table("visit_briefs")
